# Generated by Django 3.2.4 on 2021-06-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('line3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(blank=True, max_length=31)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressbook.contactlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressbook.contactlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('number', models.CharField(db_index=True, max_length=63)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Fixed'), (2, 'Cell'), (3, 'Fax')])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressbook.contactlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=127)),
                ('long_name', models.CharField(max_length=254)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressbook.country')),
            ],
            options={
                'unique_together': {('short_name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=55)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mugshots')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug_first', models.SlugField(editable=False)),
                ('slug_last', models.SlugField(editable=False)),
                ('addresses', models.ManyToManyField(to='addressbook.Address')),
                ('emails', models.ManyToManyField(to='addressbook.Email')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressbook.prefix')),
                ('telephones', models.ManyToManyField(to='addressbook.Telephone')),
                ('websites', models.ManyToManyField(to='addressbook.Website')),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressbook.contactlocation'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressbook.state'),
        ),
    ]
