# Generated by Django 3.2.4 on 2021-06-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
        ('blog', '0004_alter_post_slug_old'),
    ]

    operations = [
    ]
