# Generated by Django 3.2.4 on 2021-06-27 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='unknown', max_length=255)),
                ('secondname', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(default='unknown', max_length=255)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('deathdate', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('U', 'Undefined'), ('M', 'Male'), ('F', 'Female')], default='U', max_length=1)),
                ('desc', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Parent-child'), ('C', 'Couple')], max_length=1)),
                ('desc', models.TextField(blank=True, null=True)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='a', to='genealogy.person')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b', to='genealogy.person')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BI', 'Birth'), ('DE', 'Death'), ('MA', 'Marriage'), ('SE', 'Separation'), ('DI', 'Divorce'), ('AD', 'Adoption'), ('MO', 'Change of address'), ('BM', 'Bar or bat mitsvah'), ('CO', 'Communion'), ('OT', 'Other')], max_length=2)),
                ('desc', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('protagonist', models.ManyToManyField(related_name='events', to='genealogy.Person')),
            ],
        ),
    ]
